spring:
  application:
    name: sampleapp-name
  jpa:
    open-in-view: false # be Enterprise my friend

springfox:
  documentation:
    service-version: 1

# NEEDED since Boot 2.x!
# Charset of HTTP requests and responses. Added to the "Content-Type"
# header if not set explicitly.
spring.http.encoding.charset: UTF-8
# Enable http encoding support.
spring.http.encoding.enabled: true
# Force the encoding to the configured charset on HTTP requests and responses.
spring.http.encoding.force: true